swagger: '2.0'
info:
  title: Automile ClientApi ResourceOwnerExpenseReportRowV2 API
  version: v1
tags:
- name: ResourceOwnerExpenseReportRowV2
paths:
  /v1/resourceowner/expensereportrow/{expenseReportRowId}:
    get:
      tags:
      - ResourceOwnerExpenseReportRowV2
      summary: Get expense report row
      description: Only expense report row that the user has access to are accessible.
      operationId: GetResourceExpenseReportRow
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: path
        name: expenseReportRowId
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: The expense report row is returned
          schema:
            $ref: '#/definitions/ExpenseReportRowModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
    put:
      tags:
      - ResourceOwnerExpenseReportRowV2
      summary: Updates the given expense report row
      description: This will update the given expense report row id with a new model.
      operationId: EditResourceOwnerExpenseReportRow
      consumes:
      - application/json
      - text/json
      - application/*+json
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: path
        name: expenseReportRowId
        description: The expense report row id
        required: true
        type: integer
        format: int32
      - in: body
        name: body
        description: The new expense report row model
        schema:
          $ref: '#/definitions/ExpenseReportRowEditModel'
      responses:
        '200':
          description: The expense report row was saved
        '400':
          description: Bad request, could occur for a number of cases, see returned message
          schema:
            $ref: '#/definitions/ProblemDetails'
        '403':
          description: Request is forbidden, could occur for a number of reasons, see returned message
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not found, the expense report row you tried to update can't be found
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Internal server error
      security:
      - oauth2: []
    delete:
      tags:
      - ResourceOwnerExpenseReportRowV2
      summary: Removes the given expense report row
      operationId: DeleteResourceOwnerExpenseReportRow
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: path
        name: expenseReportRowId
        description: The expense report row id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: The expense report row has been deleted
        '403':
          description: Request is forbidden, could occur for a number of reasons, see returned message
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not found, the expense report row you tried to remove can't be found
          schema:
            $ref: '#/definitions/ProblemDetails'
        '500':
          description: Internal server error
      security:
      - oauth2: []
  /v1/resourceowner/expensereportrow:
    post:
      tags:
      - ResourceOwnerExpenseReportRowV2
      summary: Create an expense report row
      description: ''
      operationId: CreateExpenseReportRow
      consumes:
      - application/json
      - text/json
      - application/*+json
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/ExpenseReportRowCreateModel'
      responses:
        '200':
          description: A header link containing the URL to the newly created resource
        '500':
          description: Internal server error
      security:
      - oauth2: []
definitions:
  ExpenseReportRowContentModel:
    type: object
    properties:
      ExpenseReportRowContentId:
        format: int32
        type: integer
      ExpenseReportRowId:
        format: int32
        type: integer
      ContentType:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        type: integer
      ContentFileName:
        type: string
    additionalProperties: false
  ExpenseReportRowEditModel:
    type: object
    properties:
      AmountInCurrency:
        format: double
        type: number
      VATInCurrency:
        format: double
        type: number
      ISO4217CurrencyCode:
        type: string
      Notes:
        type: string
      ExpenseReportRowDateUtc:
        format: date-time
        type: string
      Category:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        type: integer
      CustomCategory:
        type: string
      ExpenseReportRowContent:
        type: array
        items:
          $ref: '#/definitions/ExpenseReportRowContentUpdateEditModel'
      CategoryValue:
        format: double
        type: number
      Merchant:
        type: string
    additionalProperties: false
  ProblemDetails:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        format: int32
        type: integer
      detail:
        type: string
      instance:
        type: string
    additionalProperties: {}
  ExpenseReportRowContentCreateModel:
    type: object
    properties:
      ExpenseReportRowId:
        format: int32
        type: integer
      Data:
        type: string
      ContentType:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        type: integer
    additionalProperties: false
  ExpenseReportRowModel:
    type: object
    properties:
      ExpenseReportRowId:
        format: int32
        type: integer
      ExpenseReportId:
        format: int32
        type: integer
      AmountInCurrency:
        format: double
        type: number
      VATInCurrency:
        format: double
        type: number
      ISO4217CurrencyCode:
        type: string
      Notes:
        type: string
      ExpenseReportRowDateUtc:
        format: date-time
        type: string
      ExpenseReportRowContent:
        type: array
        items:
          $ref: '#/definitions/ExpenseReportRowContentModel'
      Category:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        type: integer
      CustomCategory:
        type: string
      CategoryValue:
        format: double
        type: number
      Merchant:
        type: string
    additionalProperties: false
  ExpenseReportRowCreateModel:
    type: object
    properties:
      ExpenseReportId:
        format: int32
        type: integer
      AmountInCurrency:
        format: double
        type: number
      VATInCurrency:
        format: double
        type: number
      ISO4217CurrencyCode:
        type: string
      Notes:
        type: string
      Category:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        type: integer
      ExpenseReportRowDateUtc:
        format: date-time
        type: string
      ExpenseReportRowContent:
        type: array
        items:
          $ref: '#/definitions/ExpenseReportRowContentCreateModel'
      CustomCategory:
        type: string
      CategoryValue:
        format: double
        type: number
      Merchant:
        type: string
    additionalProperties: false
  ExpenseReportRowContentUpdateEditModel:
    type: object
    properties:
      ExpenseReportRowContentId:
        format: int32
        type: integer
      ExpenseReportRowId:
        format: int32
        type: integer
      Data:
        type: string
      ContentType:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        type: integer
    additionalProperties: false
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://api.automile.com/login/
    scopes:
      read: Read access to protected resources
      write: Write access to protected resources
    description: OAuth2 Implicit Grant
