swagger: '2.0'
info:
  title: Automile ClientApi ResourceOwnerExpenseReportRowContent3V2 API
  version: v1
tags:
- name: ResourceOwnerExpenseReportRowContent3V2
paths:
  /v1/resourceowner/expensereportrowcontent3/{expenseReportRowContentId}:
    get:
      tags:
      - ResourceOwnerExpenseReportRowContent3V2
      summary: Get expense report row content
      description: Only expense report row content that the user has access to are accessible.
      operationId: GetResourceExpenseReportRowContent3
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: path
        name: expenseReportRowContentId
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: The expense report row content is returned
          schema:
            $ref: '#/definitions/ExpenseReportRowContentModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
    put:
      tags:
      - ResourceOwnerExpenseReportRowContent3V2
      summary: Updates the given expense report row content
      description: This will update the given expense report row content id with a new model.
      operationId: EditResourceOwnerExpenseReportRowContent3
      consumes:
      - application/json
      - text/json
      - application/*+json
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: path
        name: expenseReportRowContentId
        description: The expense report row id
        required: true
        type: integer
        format: int32
      - in: body
        name: body
        description: The new expense report row model
        schema:
          $ref: '#/definitions/ExpenseReportRowContentEditModel'
      responses:
        '200':
          description: The expense report row content was saved
        '500':
          description: Internal server error
        '400':
          description: Bad request, could occur for a number of cases, see returned message
          schema:
            $ref: '#/definitions/ProblemDetails'
        '403':
          description: Request is forbidden, could occur for a number of reasons, see returned message
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not found, the expense report row you tried to update can't be found
          schema:
            $ref: '#/definitions/ProblemDetails'
      security:
      - oauth2: []
    delete:
      tags:
      - ResourceOwnerExpenseReportRowContent3V2
      summary: Removes the given expense report row content
      operationId: DeleteResourceOwnerExpenseReportRowContent3
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: path
        name: expenseReportRowContentId
        description: The expense report row id
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: The expense report row has been deleted
        '500':
          description: Internal server error
        '403':
          description: Request is forbidden, could occur for a number of reasons, see returned message
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not found, the expense report row you tried to remove can't be found
          schema:
            $ref: '#/definitions/ProblemDetails'
      security:
      - oauth2: []
  /v1/resourceowner/expensereportrowcontent3:
    get:
      tags:
      - ResourceOwnerExpenseReportRowContent3V2
      summary: Get all expense report row content belonging to a expense report row
      description: Only expense report row content that the user has access to are accessible.
      operationId: GetResourceExpenseReportRowContentById3
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: query
        name: expenseReportRowId
        type: integer
        format: int32
      responses:
        '200':
          description: A list of expense report row content is returned
          schema:
            $ref: '#/definitions/ExpenseReportRowContentModel'
        '500':
          description: Internal server error
      security:
      - oauth2: []
    post:
      tags:
      - ResourceOwnerExpenseReportRowContent3V2
      summary: Create an expense report row
      description: ''
      operationId: CreateExpenseReportRowContent3
      consumes:
      - application/json
      - text/json
      - application/*+json
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/ExpenseReportRowContentCreateModel'
      responses:
        '200':
          description: A header link containing the URL to the newly created resource
        '500':
          description: Internal server error
      security:
      - oauth2: []
definitions:
  ProblemDetails:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        format: int32
        type: integer
      detail:
        type: string
      instance:
        type: string
    additionalProperties: {}
  ExpenseReportRowContentCreateModel:
    type: object
    properties:
      ExpenseReportRowId:
        format: int32
        type: integer
      Data:
        type: string
      ContentType:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        type: integer
    additionalProperties: false
  ExpenseReportRowContentModel:
    type: object
    properties:
      ExpenseReportRowContentId:
        format: int32
        type: integer
      ExpenseReportRowId:
        format: int32
        type: integer
      ContentType:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        type: integer
      ContentFileName:
        type: string
    additionalProperties: false
  ExpenseReportRowContentEditModel:
    type: object
    properties:
      Data:
        type: string
      ContentType:
        format: int32
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        type: integer
    additionalProperties: false
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://api.automile.com/login/
    scopes:
      read: Read access to protected resources
      write: Write access to protected resources
    description: OAuth2 Implicit Grant
